services:

  home:
    build: ./home
    image: home:4.0
    ports:
      - "3000:80"
    container_name: home

  usuarios:
    build: ./usuarios
    container_name: usuarios
    ports:
      - "5001:5000"  
    env_file:
      - .env
    depends_on:
      - mysqlusuarios

  productos:
    build: ./productos
    container_name: productos
    ports:
      - "5002:5000"  
    env_file:
      - .env
    depends_on:
      - mysqlproductos

  pedidos:
    build: ./pedidos
    container_name: pedidos
    ports:
      - "5003:5000"  
    env_file:
      - .env
    depends_on:
      - mysqlpedidos

  mysqlpedidos:
    image: mysql:8.0
    container_name: mysqlpedidos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_db
    ports:
      - "3309:3306"
    volumes:
      - pedidos_data:/var/lib/mysql
      - ./pedidos/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysqlproductos:
    image: mysql:8.0
    container_name: mysqlproductos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productos_db
    ports:
      - "3307:3306"
    volumes:
      - productos_data:/var/lib/mysql
      - ./productos/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysqlusuarios:
    image: mysql:8.0
    container_name: mysqlusuarios
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3308:3306"
    volumes:
      - usuarios_data:/var/lib/mysql
      - ./usuarios/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pedidos_data:
  productos_data:
  usuarios_data: