services:

  home:
    image: home:4.0
    ports:
      - "3000:80"
    container_name: home

  usuarios:
    build: ./usuarios
    container_name: usuarios
    ports:
      - "5001:5000"  
    env_file:
    - .env  

  productos:
    build: ./productos
    container_name: productos
    ports:
      - "5002:5000"  
    env_file:
    - .env  

  pedidos:
    image: alpine
    container_name: pedidos

  mysqlpedidos:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos
    ports:
      - "3306:3306"
    volumes:
      - mysqlpedidos:/var/lib/mysql

volumes:
  mysqlpedidos: